---
# tasks file for start-ec2-instances
- name: Get EC2 instance info from AWS
  ec2_instance_info:
    filters: "{{ filters }}"
    region: "{{ region }}"
  register: ec2

- name: Create list of AWS EC2 instance IDs
  set_fact:
    instance_ids: "{{ instance_ids | default([]) }} + [ '{{ item.instance_id }}' ]"
  loop: "{{ ec2.instances }}"

- name: Start EC2 instances using list of instance IDs
  ec2_instance:
    instance_ids: "{{ instance_ids }}"
    region: "{{ region }}"
    state: running
