---
# defaults file for deploy-rhel-ec2-instance

#image: No default, must set when calling role
#region: No default, must set when calling role
#vpc_subnet_id: No default, must set when calling role
#security_groups: No default, must set when calling role

count: 1
instance_type: "t3.micro"
host_groups:
- launched_rhel_instances
project: "my-lab-environment"
purpose: "RHEL lab system"
os_version: "rhel"
volumes:
- device_name: /dev/sda1
  volume_type: gp2
  volume_size: 10
